# Generated by Django 5.2.17 on 2026-10-01 14:13

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancelamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('tratamento_financeiro', models.CharField(choices=[('SEM_COBRANCA', 'Sem cobrança'), ('DEVOLVER_PAGAMENTO', 'Devolver pagamento'), ('MANTER_CREDITO', 'Manter como crédito'), ('OUTRO', 'Outro')], max_length=25)),
                ('registrado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Cancelamento',
                'verbose_name_plural': 'Cancelamentos',
            },
        ),
        migrations.CreateModel(
            name='Estorno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('motivo', models.TextField()),
                ('registrado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Estorno',
                'verbose_name_plural': 'Estornos',
                'ordering': ['-registrado_em'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('forma', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('CARTAO_CREDITO', 'Cartão de crédito'), ('CARTAO_DEBITO', 'Cartão de débito'), ('TRANSFERENCIA', 'Transferência'), ('OUTRO', 'Outro')], max_length=20)),
                ('situacao', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado'), ('ESTORNADO', 'Estornado'), ('CANCELADO', 'Cancelado')], default='CONFIRMADO', max_length=15)),
                ('pago_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('referencia', models.CharField(blank=True, max_length=255)),
                ('identificador_operacao', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-pago_em'],
            },
        ),
    ]
