# Generated by Django 5.2.17 on 2026-10-01 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financeiro', '0002_initial'),
        ('ordens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelamento',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cancelamentos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estorno',
            name='autorizado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estornos_autorizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='ordem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='ordens.ordemservico'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estorno',
            name='pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estornos', to='financeiro.pagamento'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['situacao', 'pago_em'], name='financeiro__situaca_70b756_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['ordem', 'pago_em'], name='financeiro__ordem_i_aee149_idx'),
        ),
        migrations.AddConstraint(
            model_name='pagamento',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='pagamento_valor_maior_que_zero'),
        ),
        migrations.AddConstraint(
            model_name='estorno',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='estorno_valor_maior_que_zero'),
        ),
    ]
