# Generated by Django 5.2.17 on 2026-10-01 14:13

import apps.ordens.models
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('caminho', models.FileField(upload_to='ordens/anexos/%Y/%m/')),
                ('tipo', models.CharField(max_length=100)),
                ('tamanho', models.PositiveBigIntegerField()),
                ('categoria', models.CharField(choices=[('ENTRADA', 'Condições de entrada'), ('ORCAMENTO', 'Orçamento'), ('EVIDENCIA', 'Evidência'), ('COMPROVANTE', 'Comprovante'), ('OUTRO', 'Outro')], max_length=20)),
                ('enviado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
                'ordering': ['-enviado_em'],
            },
        ),
        migrations.CreateModel(
            name='AtividadeServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DIAGNOSTICO', 'Diagnóstico'), ('REPARO', 'Reparo'), ('TESTE', 'Teste'), ('DEVOLUCAO', 'Devolução'), ('OUTRO', 'Outro')], max_length=20)),
                ('descricao', models.TextField()),
                ('registrado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('resultado', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Atividade de serviço',
                'verbose_name_plural': 'Atividades de serviço',
                'ordering': ['-registrado_em'],
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recebedor', models.CharField(max_length=150)),
                ('identificacao', models.CharField(blank=True, max_length=100)),
                ('entregue_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
            },
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(default=apps.ordens.models.gerar_numero_ordem, editable=False, max_length=20, unique=True)),
                ('defeito_relatado', models.TextField()),
                ('condicoes_entrada', models.TextField()),
                ('acessorios', models.TextField(blank=True)),
                ('diagnostico', models.TextField(blank=True)),
                ('situacao', models.CharField(choices=[('RECEBIDA', 'Recebida'), ('EM_DIAGNOSTICO', 'Em diagnóstico'), ('AGUARDANDO_APROVACAO', 'Aguardando aprovação'), ('EM_REPARO', 'Em reparo'), ('AGUARDANDO_PECA', 'Aguardando peça'), ('EM_TESTES', 'Em testes'), ('PREPARAR_DEVOLUCAO', 'Preparar devolução'), ('PRONTA_ENTREGA', 'Pronta para entrega'), ('ENTREGUE', 'Entregue'), ('CANCELADA', 'Cancelada')], default='RECEBIDA', max_length=30)),
                ('situacao_financeira', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PARCIAL', 'Parcial'), ('QUITADA', 'Quitada'), ('ESTORNADA', 'Estornada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=10)),
                ('entrada_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('previsao_entrega', models.DateField(blank=True, null=True)),
                ('conclusao_em', models.DateTimeField(blank=True, null=True)),
                ('versao_registro', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Ordem de serviço',
                'verbose_name_plural': 'Ordens de serviço',
                'ordering': ['-entrada_em'],
            },
        ),
        migrations.CreateModel(
            name='PecaUtilizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)])),
                ('custo_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('utilizada_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Peça utilizada',
                'verbose_name_plural': 'Peças utilizadas',
                'ordering': ['-utilizada_em'],
            },
        ),
    ]
