# Generated by Django 5.2.17 on 2026-10-01 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('equipamentos', '0001_initial'),
        ('ordens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anexo',
            name='enviado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anexos_enviados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atividadeservico',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atividades_servico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrega',
            name='autorizacao_excecao_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entregas_autorizadas_excepcionalmente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrega',
            name='comprovante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entregas_comprovadas', to='ordens.anexo'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='atendente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_atendidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens', to='equipamentos.equipamento'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='ordem_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retornos', to='ordens.ordemservico'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_tecnico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrega',
            name='ordem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='entrega', to='ordens.ordemservico'),
        ),
        migrations.AddField(
            model_name='atividadeservico',
            name='ordem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atividades', to='ordens.ordemservico'),
        ),
        migrations.AddField(
            model_name='anexo',
            name='ordem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anexos', to='ordens.ordemservico'),
        ),
        migrations.AddField(
            model_name='pecautilizada',
            name='ordem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pecas_utilizadas', to='ordens.ordemservico'),
        ),
        migrations.AddField(
            model_name='pecautilizada',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pecas_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ordemservico',
            index=models.Index(fields=['situacao', 'previsao_entrega'], name='ordens_orde_situaca_5517cb_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemservico',
            index=models.Index(fields=['tecnico', 'situacao'], name='ordens_orde_tecnico_f4fe48_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemservico',
            index=models.Index(fields=['cliente', 'entrada_em'], name='ordens_orde_cliente_93f481_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemservico',
            index=models.Index(fields=['equipamento', 'entrada_em'], name='ordens_orde_equipam_47c13f_idx'),
        ),
        migrations.AddConstraint(
            model_name='ordemservico',
            constraint=models.CheckConstraint(condition=models.Q(('versao_registro__gte', 1)), name='ordem_versao_registro_positiva'),
        ),
        migrations.AddIndex(
            model_name='atividadeservico',
            index=models.Index(fields=['ordem', 'registrado_em'], name='ordens_ativ_ordem_i_2434f5_idx'),
        ),
        migrations.AddIndex(
            model_name='atividadeservico',
            index=models.Index(fields=['tecnico', 'registrado_em'], name='ordens_ativ_tecnico_6a390e_idx'),
        ),
        migrations.AddIndex(
            model_name='anexo',
            index=models.Index(fields=['ordem', 'categoria'], name='ordens_anex_ordem_i_8474f9_idx'),
        ),
        migrations.AddConstraint(
            model_name='anexo',
            constraint=models.CheckConstraint(condition=models.Q(('tamanho__gt', 0)), name='anexo_tamanho_maior_que_zero'),
        ),
        migrations.AddConstraint(
            model_name='pecautilizada',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='peca_quantidade_maior_que_zero'),
        ),
        migrations.AddConstraint(
            model_name='pecautilizada',
            constraint=models.CheckConstraint(condition=models.Q(('custo_unitario__gte', 0)), name='peca_custo_nao_negativo'),
        ),
    ]
