# Generated by Django 5.2.17 on 2026-10-01 14:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAlteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=100)),
                ('dados_anteriores', models.JSONField(blank=True, null=True)),
                ('dados_novos', models.JSONField(blank=True, null=True)),
                ('justificativa', models.TextField(blank=True)),
                ('registrado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Histórico de alteração',
                'verbose_name_plural': 'Histórico de alterações',
                'ordering': ['-registrado_em'],
            },
        ),
    ]
