# Generated by Django 5.2.17 on 2026-10-01 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditoria', '0001_initial'),
        ('ordens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoalteracao',
            name='ordem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico', to='ordens.ordemservico'),
        ),
    ]
