# Generated by Django 5.2.17 on 2026-10-01 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditoria', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoalteracao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alteracoes_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='historicoalteracao',
            index=models.Index(fields=['ordem', 'registrado_em'], name='auditoria_h_ordem_i_6c8625_idx'),
        ),
        migrations.AddIndex(
            model_name='historicoalteracao',
            index=models.Index(fields=['usuario', 'registrado_em'], name='auditoria_h_usuario_a6d57a_idx'),
        ),
    ]
