# Generated by Django 5.2.17 on 2026-10-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('documento', models.CharField(blank=True, max_length=30)),
                ('endereco', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nome'], name='clientes_cl_nome_b2cdde_idx'), models.Index(fields=['documento'], name='clientes_cl_documen_76f212_idx')],
            },
        ),
    ]
