# Generated by Django 5.2.17 on 2026-10-01 14:13

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DecisaoOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decisao', models.CharField(choices=[('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado')], max_length=10)),
                ('data', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('canal', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('TELEFONE', 'Telefone'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'E-mail'), ('OUTRO', 'Outro')], max_length=15)),
                ('nome_autorizador', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Decisão de orçamento',
                'verbose_name_plural': 'Decisões de orçamento',
            },
        ),
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SERVICO', 'Serviço'), ('PECA', 'Peça'), ('OUTRO', 'Outro')], max_length=10)),
                ('descricao', models.CharField(max_length=255)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'verbose_name': 'Item de orçamento',
                'verbose_name_plural': 'Itens de orçamento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.PositiveIntegerField()),
                ('situacao', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ENVIADO', 'Enviado'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado'), ('EXPIRADO', 'Expirado'), ('SUBSTITUIDO', 'Substituído')], default='RASCUNHO', max_length=20)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('valido_ate', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ['-versao'],
            },
        ),
    ]
