# Generated by Django 5.2.17 on 2026-10-01 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orcamentos', '0002_initial'),
        ('ordens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='decisaoorcamento',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisoes_orcamento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='criador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='ordem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='ordens.ordemservico'),
        ),
        migrations.AddField(
            model_name='itemorcamento',
            name='orcamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='orcamentos.orcamento'),
        ),
        migrations.AddField(
            model_name='decisaoorcamento',
            name='orcamento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='decisao', to='orcamentos.orcamento'),
        ),
        migrations.AddIndex(
            model_name='orcamento',
            index=models.Index(fields=['situacao', 'valido_ate'], name='orcamentos__situaca_0f19fd_idx'),
        ),
        migrations.AddIndex(
            model_name='orcamento',
            index=models.Index(fields=['ordem', 'versao'], name='orcamentos__ordem_i_8fb465_idx'),
        ),
        migrations.AddConstraint(
            model_name='orcamento',
            constraint=models.UniqueConstraint(fields=('ordem', 'versao'), name='orcamento_ordem_versao_unicas'),
        ),
        migrations.AddConstraint(
            model_name='orcamento',
            constraint=models.CheckConstraint(condition=models.Q(('versao__gte', 1)), name='orcamento_versao_positiva'),
        ),
        migrations.AddConstraint(
            model_name='itemorcamento',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='item_orcamento_quantidade_maior_que_zero'),
        ),
        migrations.AddConstraint(
            model_name='itemorcamento',
            constraint=models.CheckConstraint(condition=models.Q(('valor_unitario__gte', 0)), name='item_orcamento_valor_nao_negativo'),
        ),
    ]
