import { bindShell, api, formatNumber, escapeHtml, formatDateTime, handleAuthError, icon, jsonOptions, openModal, state, statusTag, unwrap, closeModal, showToast } from "../shared/core.js";

const root=document.querySelector("[data-screen-slot]");bindShell();

export async function render(options={}){const term=encodeURIComponent(state.search.usuarios||"");setLoading();try{const data=unwrap(await api(options.pageUrl||`/usuarios/?page=1${term?`&q=${term}`:""}`));state.pages.usuarios={next:data.next||"",previous:data.previous||""};state.cache.usuarios=data.results;renderRows(data.results,data.count);}catch(error){if(handleAuthError(error))return;showEmpty(error.message);}bind(root);}
function setLoading(){root.querySelector("[data-table-wrap]").hidden=true;const empty=root.querySelector("[data-empty-state]");empty.classList.remove("hidden");empty.innerHTML='<div class="page-loading"><span class="spinner" role="status" aria-label="Carregando usuários"></span></div>';}
function renderRows(records,count){const table=root.querySelector("[data-table-wrap]"),body=root.querySelector("[data-table-body]"),empty=root.querySelector("[data-empty-state]");root.querySelector("#search-usuarios").value=state.search.usuarios||"";if(!records.length){showEmpty("Nenhum usuário encontrado.");return;}body.innerHTML=records.map((item)=>`<tr><td class="primary-cell">${escapeHtml(item.nome)}<div class="muted-cell" style="margin-top:4px">${escapeHtml(item.email||"Sem e-mail")}</div></td><td>${escapeHtml(item.login)}</td><td>${statusTag(item.perfil,item.perfil_display||item.perfil)}</td><td>${statusTag(item.ativo?"APROVADO":"CANCELADA",item.ativo?"Ativo":"Inativo")}</td><td class="muted-cell">${formatDateTime(item.date_joined)}</td><td class="right"><button class="icon-button" data-action="user-detail" data-id="${item.id}" aria-label="Ver usuário">${icon("eye")}</button></td></tr>`).join("");table.hidden=false;empty.classList.add("hidden");updatePagination("usuarios",count,records.length);}
function updatePagination(view, count, loaded) {
  const page = state.pages[view] || {};
  const container = root.querySelector("[data-pagination]");
  if (!count && !page.next && !page.previous) { container.innerHTML = ""; return; }
  container.innerHTML = `<div style="display:flex;justify-content:space-between;align-items:center;gap:12px;padding:14px 18px;border-top:1px solid var(--border);color:var(--muted);font-size:11px"><span>${formatNumber(loaded)} de ${formatNumber(count)} registros</span><span style="display:flex;gap:6px"><button class="button button-secondary button-sm" data-action="page" data-view="${view}" data-url="${escapeHtml(page.previous || "")}" ${page.previous ? "" : "disabled"}>Anterior</button><button class="button button-secondary button-sm" data-action="page" data-view="${view}" data-url="${escapeHtml(page.next || "")}" ${page.next ? "" : "disabled"}>Próxima</button></span></div>`;
}

function showEmpty(message){const empty=root.querySelector("[data-empty-state]");root.querySelector("[data-table-wrap]").hidden=true;empty.classList.remove("hidden");empty.innerHTML=`<span class="icon-wrap">${icon("info")}</span><p>${escapeHtml(message)}</p>`;root.querySelector("[data-pagination]").innerHTML="";}
function bind(element){if(element.dataset.bound==="true")return;element.dataset.bound="true";element.addEventListener("submit",(event)=>{if(!event.target.matches("[data-collection-search]"))return;event.preventDefault();state.search.usuarios=new FormData(event.target).get("q")||"";render();});element.addEventListener("click",(event)=>{const action=event.target.closest("[data-action]");if(action?.dataset.action==="new-user")openCreate();if(action?.dataset.action==="user-detail")openDetail(action.dataset.id);if(action?.dataset.action==="refresh-screen")render();if(action?.dataset.action==="page"&&action.dataset.url)render({pageUrl:action.dataset.url});});}
function openCreate(){openModal("Novo usuário","Defina o perfil e o acesso inicial da pessoa na operação",`<form id="user-form"><div class="form-grid"><div class="field"><label>Nome <span>*</span></label><input name="nome" required /></div><div class="field"><label>Login <span>*</span></label><input name="login" required /></div><div class="field"><label>E-mail</label><input name="email" type="email" /></div><div class="field"><label>Perfil <span>*</span></label><select name="perfil" required><option value="ATENDENTE">Atendente</option><option value="TECNICO">Técnico</option><option value="GERENTE">Gerente</option></select></div><div class="field full"><label>Senha inicial <span>*</span></label><input name="password" type="password" minlength="8" required /></div></div></form>`,`<button class="button button-secondary" data-action="close-modal">Cancelar</button><button class="button button-primary" form="user-form" type="submit">${icon("check")}Salvar</button>`);document.getElementById("user-form").addEventListener("submit",async(event)=>{event.preventDefault();try{await api("/usuarios/",jsonOptions(Object.fromEntries(new FormData(event.currentTarget).entries())));closeModal();showToast("Usuário cadastrado.","success");await render();}catch(error){if(!handleAuthError(error))showToast(error.message,"error");}});}
function openDetail(id){const item=(state.cache.usuarios||[]).find((user)=>String(user.id)===String(id));if(!item)return;openModal(item.nome,"Dados do usuário",`<div class="detail-list"><div><div class="detail-item-label">Login</div><div class="detail-item-value">${escapeHtml(item.login)}</div></div><div><div class="detail-item-label">Perfil</div><div class="detail-item-value">${statusTag(item.perfil,item.perfil_display||item.perfil)}</div></div><div><div class="detail-item-label">Status</div><div class="detail-item-value">${statusTag(item.ativo?"APROVADO":"CANCELADA",item.ativo?"Ativo":"Inativo")}</div></div><div><div class="detail-item-label">Entrada</div><div class="detail-item-value">${formatDateTime(item.date_joined)}</div></div></div>`,'<button class="button button-secondary" data-action="close-modal">Fechar</button>');}
render();







